# Generated by Django 4.2.7 on 2024-06-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(blank=True, choices=[('color', 'variation 1'), ('size', 'variation 2')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
