# Generated by Django 4.2.7 on 2024-06-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousfeedback',
            name='type',
            field=models.CharField(choices=[('service_delivery', 'Service Delivery'), ('product_delivery', 'Product Delivery')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('service_delivery', 'Service Delivery'), ('product_delivery', 'Product Delivery')], max_length=100, verbose_name='Type'),
        ),
    ]
