# Generated by Django 4.2.7 on 2024-06-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_driver_alter_engineer_options_and_more'),
        ('appointment', '0006_alter_appointment_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.engineer'),
        ),
    ]
