# Generated by Django 4.2.7 on 2024-06-17 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_assigned_engineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.payment')),
            ],
            options={
                'verbose_name': 'receipt',
                'ordering': ('-issued_at',),
            },
        ),
    ]
