# Generated by Django 4.2.7 on 2024-06-17 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 17, 5, 45, tzinfo=datetime.timezone.utc)),
        ),
    ]
