# Generated by Django 5.0.6 on 2024-06-17 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0010_alter_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2024, 6, 17, 18, 9, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
