# Generated by Django 4.2.7 on 2024-06-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_engineer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name': 'Engineer', 'verbose_name_plural': 'Engineers'},
        ),
    ]
