# Generated by Django 4.2.7 on 2024-06-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.ImageField(blank=True, default='../static/images/avatars/user.png', null=True, upload_to='userprofile/')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Profile',
                'verbose_name_plural': 'Supplier Profiles',
            },
        ),
    ]
