# Generated by Django 4.2.7 on 2024-06-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_finance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name': 'Finance Officer', 'verbose_name_plural': 'Finance Officers'},
        ),
    ]
