# Generated by Django 4.2.7 on 2024-06-10 15:59

import accounts.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_finance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
            bases=('accounts.account',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name': 'Mechanic', 'verbose_name_plural': 'Mechanic'},
        ),
        migrations.AlterModelOptions(
            name='storekeeper',
            options={'verbose_name': 'Inventory Manager', 'verbose_name_plural': 'Inventory Manager'},
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[accounts.validators.validate_phone_number]),
        ),
    ]
