# Generated by Django 4.2.7 on 2024-06-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_supplierprofile'),
        ('supplier', '0002_alter_commodity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequest',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier'),
        ),
    ]
