# Generated by Django 4.2.7 on 2024-06-11 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_payment_product_tenderrequest_tenderresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderrequest',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
