# Generated by Django 4.2.7 on 2024-06-13 04:37

from django.db import migrations, models
import supplier.validators


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_payment_payment_id_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(help_text='Enter a 10 characters without spaces', max_length=10, unique=True, validators=[supplier.validators.validate_payment_id]),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
