# Generated by Django 4.2.7 on 2024-06-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_alter_payment_payment_id_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderresponse',
            name='admin_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
