# Generated by Django 4.2.7 on 2024-06-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_tenderresponse_admin_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderrequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
