# Generated by Django 4.2.7 on 2024-06-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_city_alter_order_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('paypal', 'Paypal')], default='mpesa', max_length=100),
        ),
    ]
