# Generated by Django 4.2.7 on 2024-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('mpesa', 'Mpesa')], default='mpesa', max_length=100),
        ),
    ]
