# Generated by Django 4.2.7 on 2024-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('paypal', 'Paypal')], default='mpesa', max_length=100),
        ),
    ]
