# Generated by Django 4.2.7 on 2024-06-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('mpesa', 'Mpesa')], default='mpesa', max_length=100),
        ),
    ]
