# Generated by Django 4.2.7 on 2024-06-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(choices=[('roysambu', 'Roysambu'), ('soutb', 'South B'), ('imara', 'Imara'), ('zimmerman', 'Zimmerman'), ('kasarani', 'Kasarani'), ('karen', 'Karen'), ('mbotela', 'Mbotela'), ('mukuru', 'Mukuru')], default='Choose Your Pick up Point', max_length=100),
        ),
        migrations.CreateModel(
            name='TrackingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('packaging', 'Packaging'), ('ontransit', 'On Transit'), ('arrived', 'arrived')], default='packaging', max_length=100)),
                ('pick_status', models.CharField(choices=[('onpickuppoint', 'On Pick Up Point'), ('picked', 'Picked Up')], default='onpickuppoint', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Track order',
                'verbose_name_plural': 'Track Orders',
            },
        ),
    ]
