# Generated by Django 4.2.7 on 2024-06-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_point',
        ),
        migrations.AlterField(
            model_name='trackingorders',
            name='status',
            field=models.CharField(choices=[('ontransit', 'On Transit'), ('arrived', 'arrived'), ('packaging', 'Packaging')], default='packaging', max_length=100),
        ),
    ]
