# Generated by Django 4.2.7 on 2024-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_pickup_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackingorders',
            name='status',
            field=models.CharField(choices=[('packaging', 'Packaging'), ('ontransit', 'On Transit'), ('arrived', 'Arrived')], default='packaging', max_length=100),
        ),
    ]
