# Generated by Django 4.2.7 on 2024-06-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(choices=[('packaging', 'Packaging'), ('ontransit', 'On Transit')], default='packaging', max_length=20),
        ),
        migrations.DeleteModel(
            name='TrackingOrders',
        ),
    ]
