# Generated by Django 4.2.7 on 2024-06-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_track_delete_trackingorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.CharField(choices=[('Packaging', 'Packaging'), ('On Transit', 'On Transit')], default='packaging', max_length=20),
        ),
    ]
