# Generated by Django 4.2.7 on 2024-06-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.CharField(choices=[('Packaging', 'Packaging'), ('On Transit', 'On Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Packaging', max_length=20),
        ),
    ]
