# Generated by Django 4.2.7 on 2024-06-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_driver_alter_engineer_options_and_more'),
        ('orders', '0022_rename_created_at_shipment_shipped_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='accounts.driver'),
        ),
    ]
