# Generated by Django 4.2.7 on 2024-06-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_shipment_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
