# Generated by Django 4.2.7 on 2024-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_shipment_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
    ]
