# Generated by Django 4.2.7 on 2024-06-13 09:08

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_shipment_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=10, unique=True, validators=[orders.validators.validate_payment_id]),
        ),
    ]
