# Generated by Django 4.2.7 on 2024-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
