# Generated by Django 4.2.7 on 2024-06-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_shipment_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='read',
            new_name='received',
        ),
    ]
